#!/bin/zsh

set -ex

/opt/conda/bin/conda init zsh
# /opt/conda/bin/conda activate base

# source ${PYENV}/bin/activate

git config --global user.email ${EMAIL:-"name@example.com"}
git config --global user.name ${FULLNAME:-"Name Surname"}

cd ${WORKSPACE_PATH}
sudo mkdir -p .theia
cp -nR ${BUILD_PATH}/.theia/* ${WORKSPACE_PATH}/.theia
cp -nR ${BUILD_PATH}/.editorconfig ${WORKSPACE_PATH}/.editorconfig

cd ${WORKSPACE_PATH}
sudo chown -R theia:theia .theia 

if [[ -x "bootstrap.sh" ]]; then
    ./bootstrap.sh
fi

cd ${BUILD_PATH} && /usr/bin/tini -v -- yarn theia start ${WORKSPACE_PATH} --hostname=0.0.0.0 --port=${PORT_THEIA}
