#!/bin/zsh

setopt EXTENDED_GLOB
set -ex

for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done


CUST='
# Implement your requirements...

# Port selection
BASE_PORT=$PORT
TTY_NO=$(echo $TTY | tr -dc "0-9")

# exporting terminal-specific port
export PORT=$(($BASE_PORT + $TTY_NO))
# patching term no
export PS1="${PORT}|${PS1:-}"
'

echo $CUST >> "$HOME/.zshrc"

